# ======================================
# MENÚ PRINCIPAL - JORNADAS ELEKIN
# ======================================

main:
main:
  - name: "Tour"
    url: "/tour/"
    weight: 1
    
  - name: "Jornadas"
    url: "/jornadas/"
    weight: 2

  - name: "Investigación"
    url: "/investigacion/"
    weight: 3

  - name: "Equipo"
    url: "/equipo/"
    weight: 4

  - name: "Proyectos"
    url: "/proyectos/"
    weight: 5

  - name: "Publicaciones"
    url: "/publicaciones/"
    weight: 6

  - name: "Contacto"
    url: "/contacto/"
    weight: 7
